config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#index'

  get '/search_suggestions', to: 'search#autocomplete'

  post '/votes/upvote', to: 'votes#upvote'
  post '/votes/downvote', to: 'votes#downvote'
  post '/requests/arrange', to: 'requests#arrange'
  post '/requests/destroy', to: 'requests#destroy'
  get '/playlists/:id/youtube_search', to: 'search#youtube_search'

  # Authentication
  match '/auth/:provider/callback', to: 'sessions#create', via: 'get'
  match '/auth/failure', to: redirect('/'), via: 'get'
  get 'logout', to: 'sessions#destroy'

  # Dashboard
  get '/dashboard', to: 'users#dashboard'

  # Tags
  get 'tags/:tag', to: 'playlists#index', as: :tag
  # Search by Tags and playlist title
  get '/search', to: 'search#playlist_search'

  resources :subscriptions, :only => [:create, :destroy, :update]
  resources :votes, :only => [:upvote, :downvote]
  resources :requests, :only => [:arrange, :destroy]
  resources :songs, :only => [:create, :show]
  resources :users, :only => [:show, :update]
  resources :likes, :only => [:create, :destroy]
  
  resources :playlists do 
    resources :chat_messages
  end

  resources :playlists do
    resources :songs
  end

  # 


end

app/models/chat_message.rb
class ChatMessage < ActiveRecord::Base
	belongs_to :playlist
	belongs_to :user
end

app/models/faye_server.rb
class FayeServer
	def self.broadcast(channel, data)
		message = {:channel => channel, :data => data}
		uri = URI.parse('http://localhost:9292/faye')
		Net::HTTP.post_form(uri, :message => message.to_json)
	end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :user
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :requests
  has_many :songs, through: :requests
  belongs_to :host, :class_name => "User"
  has_many :chat_messages

  has_many :subscriptions
  has_many :subscribers, through: :subscriptions

  has_many :likes
  has_many :people_who_liked_it, :through => :likes, :source => :user

  validates_uniqueness_of :host_id, :scope => "name"
  #implement dependent destroy for requests

  # taggable gem:
  acts_as_taggable

  def list_all_uid
    requests.order(:position).each_with_object([]) { |request, songs_array| songs_array << "\'#{request.song.uid}\'"}.join(",") 
  end

  def update_position(video_id_array)
    requests.each_with_index do |request, index|
      # request.position = video_id_array.index(request.song.uid)
      request.update(position: video_id_array.index(request.song.uid))
    end
  end
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist
  belongs_to :listener, :class_name => "User"
  has_many :votes
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :requests
  has_many :users, through: :requests
  has_many :playlists, through: :requests

  def self.get_song_hash_from_url(videoid)
    Yt.configuration.api_key = ENV['YOUTUBE_KEY']
    # client = YouTubeIt::Client.new(:dev_key => ENV["YOUTUBE_KEY"])
    video = Yt::Video.new id: videoid
    # binding.pry
    song_hash = {
      :name => video.title,
      :url => "https://www.youtube.com/watch?v=" + videoid,
      :uid => videoid
      }
    song_hash
  end
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :subscriber, class_name: "User"#, :foreign_key => 'host_id'

  validates_uniqueness_of :subscriber_id, :scope => [:playlist_id]
end

app/models/temp.rb
class Temp
	def self.broadcast(channel, data)
		message = {:channel => channel, :data => data}
		uri = URI.parse('http://localhost:9292/faye')
		Net::HTTP.post_form(uri, :message => message.to_json)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :host_playlists, :class_name => "Playlist", :foreign_key => 'host_id'
  has_many :requests, :foreign_key => 'listener_id'
  has_many :listener_playlists, -> { uniq }, through: :requests, :source => :playlist
  has_many :songs, through: :requests, :foreign_key => 'listener_id'
  has_many :chat_messages
  has_many :votes
  
  has_many :subscriptions, :foreign_key => 'subscriber_id'
  has_many :playlists, :through => :subscriptions

  has_many :likes
  has_many :liked_playlists, :through => :likes, :source => :playlist

  def twitter
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV['TWITTER_KEY']
      config.consumer_secret     = ENV['TWITTER_SECRET']
      config.access_token        = token
      config.access_token_secret = secret
    end
  end

  def filter_listener_playlist
    #self.listener_playlist.select where host id != listender_id
  end

  def self.find_or_create_from_auth_hash(auth_hash)
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      name: auth_hash.info.name,
      nickname: auth_hash.info.nickname,
      profile_image: auth_hash.info.image,
      profile_url: auth_hash.info.urls.Twitter,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
      )
    user
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :request
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    like = Like.create(like_params)
    flash[:notice] = "You've liked this playlist."
    redirect_to Playlist.find(params[:like][:playlist_id])
  end

  def destroy
    like = Like.find_by(like_params)
    like.destroy
    flash[:notice] = "You've unliked this playlist."
    redirect_to Playlist.find(params[:like][:playlist_id])
  end

  private
  def like_params
    params.require(:like).permit(:user_id, :playlist_id)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def create
    playlist = Playlist.find(params[:playlist_id])
    if params[:search_term_or_url] =~ /^(?:https?:\/\/)?(?:www\.)?(?:youtu\.be\/|youtube\.com(?:\/embed\/|\/v\/|\/watch\?v=|\/watch\?.+&v=))([\w-]{11})(?:.+)?$/
      song_hash = Song.get_song_hash_from_url($1)
      song = Song.find_or_create_by(song_hash)
      request = Request.find_or_create_by(
      {   :song_id => song.id, 
          :listener_id => current_user.id,
          :playlist_id => playlist.id,
          :position => playlist.requests.last.position + 1 })
    else
      song_hash = Song.get_song_hash_from_url(params[:search_term_or_url])
      song = Song.find_or_create_by(song_hash)

      if playlist.requests.maximum("position")
        request = Request.find_or_create_by(
        {   :song_id => song.id, 
            :listener_id => current_user.id,
            :playlist_id => playlist.id,
            :position => playlist.requests.maximum("position") + 1 })
      else
        request = Request.find_or_create_by(
        {   :song_id => song.id, 
            :listener_id => current_user.id,
            :playlist_id => playlist.id,
            :position => 0 }) 
      end
    end
    broadcast_information = { :request_id => "#{request.id}", 
                              :name => "#{song.name}", 
                              :vote_count => "#{request.vote_count}", 
                              :song_id => "#{request.song_id}",
                              :uid => "#{song.uid}",
                              :request_by => "#{request.listener.name}"
                            }
    FayeServer.broadcast("/playlists/#{request.playlist_id}/add", broadcast_information)
    render :nothing => true
  end

  def show
    @song = Song.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user != current_user
      flash[:notice] = "You can't edit another user."
      redirect_to @user
    else
      @user.update(:description => params[:user][:description])
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/songs/show.html.erb
<%= link_to "#{@song.name}", @song.url %>

app/views/users/_update_description.html.erb
<div id="update-description-form">
  <%= form_for(@user, :url => { :action => "update" }) do |f| %>
    <%= f.label "Enter description:" %><br>
    <%= f.text_area :description, :size => "40x5" %><br>
    <%= f.submit "Update description" %>
  <% end %>
</div>

app/views/users/dashboard.html.erb
Dashboard:

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-4">
    <img src="<%= @user.profile_image.gsub("_normal", "").gsub("http", "https") %>" alt="<%= @user.name %>'s profile picture">
  </div>

  <div class="col-md-8">
    <%= @user.name %><br>
    <a href="<%= @user.profile_url %>">@<%= @user.nickname %></a>
    <p>
      <% if @user.description %>
        <%= @user.description %><br>
        <h6><a id="update-description-link" href="#">Update description</a></h6>
        <%= render 'users/update_description' %>
      <% else %>
        <h6>You do not have a description. <a id="update-description-link" href="#">Would you like to add one?</a></h6>
        <%= render 'users/update_description' %>
      <% end %>
    </p>
  </div>
</div>

<h1><%= link_to "New Playlist", new_playlist_path %></h1>

<div class="col-md-4">
  <% if current_user.host_playlists.any? %>
    <h4>Playlists you host:</h4>
    <% current_user.host_playlists.each do |playlist| %>
      <%= link_to "#{playlist.name}", playlist_path(playlist) %><br>
    <% end %>
  <% else %>
    <h4>You currently have no playlists, <%= link_to "create one now", new_playlist_path %>.</h4>
  <% end %>
</div>

<div class="col-md-4">
  <% if current_user.subscriptions.any? %>
    <h4>Playlists you follow:</h4>
    <% current_user.subscriptions.each do |subscription| %>
      <%= link_to "#{subscription.playlist.name}", playlist_path(subscription.playlist) %><br>
    <% end %>
    <% else %>
    <h4>You are currently not following any playlists.</h4>
  <% end %>
</div>

<div class="col-md-4">
  <% if current_user.liked_playlists.any? %>
    <h4>Playlists you like:</h4>
    <% current_user.subscriptions.each do |subscription| %>
      <%= link_to "#{subscription.playlist.name}", playlist_path(subscription.playlist) %><br>
    <% end %>
    <% else %>
    <h4>You currently do not like any playlists.</h4>
  <% end %>
</div>