config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#index'

  get '/search_suggestions', to: 'search#autocomplete'

  post '/votes/upvote', to: 'votes#upvote'
  post '/votes/downvote', to: 'votes#downvote'
  post '/requests/arrange', to: 'requests#arrange'
  post '/requests/destroy', to: 'requests#destroy'
  get '/playlists/:id/youtube_search', to: 'search#youtube_search'

  # Authentication
  match '/auth/:provider/callback', to: 'sessions#create', via: 'get'
  match '/auth/failure', to: redirect('/'), via: 'get'
  get 'logout', to: 'sessions#destroy'

  # Dashboard
  get '/dashboard', to: 'users#dashboard'

  # Tags
  get 'tags/:tag', to: 'playlists#index', as: :tag
  # Search by Tags and playlist title
  get '/search', to: 'search#playlist_search'

  resources :subscriptions, :only => [:create, :destroy, :update]
  resources :votes, :only => [:upvote, :downvote]
  resources :requests, :only => [:arrange, :destroy]
  resources :songs, :only => [:create, :show]
  resources :users, :only => [:show, :update]
  resources :likes, :only => [:create, :destroy]
  
  resources :playlists do 
    resources :chat_messages
  end

  resources :playlists do
    resources :songs
  end

  # 


end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :requests
  has_many :songs, through: :requests
  belongs_to :host, :class_name => "User"
  has_many :chat_messages

  has_many :subscriptions
  has_many :subscribers, through: :subscriptions

  has_many :likes
  has_many :people_who_liked_it, :through => :likes, :source => :user

  validates_uniqueness_of :host_id, :scope => "name"
  #implement dependent destroy for requests

  # taggable gem:
  acts_as_taggable

  def list_all_uid
    requests.order(:position).each_with_object([]) { |request, songs_array| songs_array << "\'#{request.song.uid}\'"}.join(",") 
  end

  def update_position(video_id_array)
    requests.each_with_index do |request, index|
      # request.position = video_id_array.index(request.song.uid)
      request.update(position: video_id_array.index(request.song.uid))
    end
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    if params[:tag]
      @playlists = Playlist.tagged_with(params[:tag])
      @tag = params[:tag]
    else
      @playlists = Playlist.all
    end
  end

  def show
    # @client = YouTubeIt::Client.new(:dev_key => ENV['YOUTUBE_KEY'])
    @playlist = Playlist.find(params[:id])
    @songs = @playlist.list_all_uid
    @song = Song.new
    @subscription = Subscription.find_by({:playlist_id => @playlist.id, :subscriber_id => current_user.id })
    @approved_subscriptions = @playlist.subscriptions.where(:approved => true) 
    @unapproved_subscriptions = @playlist.subscriptions.where(:approved => false)
    @like = Like.find_by({:playlist_id => @playlist.id, :user_id => current_user.id })

    if @playlist.prvt && current_user.id != @playlist.host_id
      flash[:notice] = "This playlist is private!."
      redirect_to current_user
    end
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = current_user.host_playlists.build(playlist_params)
    if @playlist.save
      redirect_to @playlist
    else
      render :new
    end
  end

  def edit
    @playlist = Playlist.find(params[:id])

    if @playlist.host_id != current_user.id
      flash[:notice] = "You can't edit another user's playlist."
      redirect_to @playlist
    end
  end

  def update
    flash[:notice] = []
    @playlist = Playlist.find(params[:id])
    if @playlist.locked == true && playlist_params[:locked] == "0"
        flash[:notice] << "Playlist successfully unlocked"
    elsif @playlist.locked == false && playlist_params[:locked] == "1"
      flash[:notice] << "Playlist successfully locked"
    end
    if @playlist.prvt == true && playlist_params[:prvt] == "0"
      flash[:notice] << "Playlist successfully made public"
    elsif @playlist.prvt == false && playlist_params[:prvt] == "1"
      flash[:notice] << "Playlist successfully made private"
    end
    if playlist_params[:tag_list] != @playlist.tag_list.join(", ")
      flash[:notice] << "Tags successfully updated"
    end
    @playlist.update_attributes(playlist_params)
      redirect_to @playlist
  end

  private
  def playlist_params
    params.require(:playlist).permit(:name, :host_id, :locked, :tag_list, :prvt)
  end

end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_add_song_form.html.erb
<%= form_tag(songs_path, method: "post", :id => "add-song-form") do %>
  <%= hidden_field_tag :user_id, current_user.id %>
  <%= hidden_field_tag :playlist_id, params["id"] %>
  <%= label_tag "Enter Youtube URL or Search Term: " %>
  <%= text_field_tag :search_term_or_url %>
  <%= submit_tag "Add Song", :id => "intelligent-add-song"%>
<% end %>

app/views/playlists/_chat_box_and_form.html.erb
<div id="chat">
  <!-- actual chat box -->
  <h1>Chat:</h1>
  <div id="message-div">
    <table id="message-table" class="table" style="width:100%">
      <% @playlist.chat_messages.each do |message| %>
        <% if message.user_id == current_user.id %>
          <tr class="current_user_comment">
            <td><%= message.user.name %>: <%= message.content %></td>
          </tr>
        <% else %>
          <tr class="other_user_comment">
            <td><%= message.user.name %>: <%= message.content %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  </div>

  <%= form_for [@playlist, ChatMessage.new], :html => {:id => "chat-message-form"} do |f| %>
    <%= f.hidden_field :playlist_id, value: @playlist.id %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.text_field :content %>
    <%= f.submit "Send", :id => 'chat_send'%>
  <% end %>
</div>

app/views/playlists/_host_panel.html.erb
<!-- Settings -->
<% if @playlist.host == current_user %>
  <%= link_to "", { controller: "playlists", action: "edit" }, class: "fa fa-wrench btn fa-3x" %>
<% end %>

app/views/playlists/_like_button.html.erb
  <!-- form -->
<% if @like %>
  <%= form_for @like, :method => :delete do |f| %>   
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :playlist_id, :value => @playlist.id %>
    <%= button_tag(type: "submit", :class => "btn btn-default") do %>
      <i class="fa liked fa-thumbs-up fa-3x"></i>
    <% end %>
  <% end %>
<% else %>
  <%= form_for Like.new do |f| %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :playlist_id, :value => @playlist.id %>
    <%= button_tag(type: "submit", :class => "btn btn-default") do %>
      <i class="fa unliked fa-thumbs-up fa-3x"></i>
    <% end %>
  <% end %>
<% end %>

app/views/playlists/_like_user_box.html.erb
<% if @playlist.people_who_liked_it.count > 0 %>
  <h3>Likers: </h3>
  <% @playlist.people_who_liked_it.each do |liker| %>
    <img src="<%= liker.profile_image %>" alt="<%= liker.name %>'s profile icon.">
  <% end %>
<% end %>

app/views/playlists/_playlists_show_tags.html.erb
<p>
  <!-- using raw here. should probably have helper method to escape html -->
  Tags: <%= raw @playlist.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(", ") %>
</p>

app/views/playlists/_show_skip_button.html.erb
<%= form_tag do %>
  <%= button_tag(type: "submit", :id => "skip", :class => "btn btn-default") do %>
    <i class="fa liked fa-step-forward"></i>
  <% end %>
<% end %>

app/views/playlists/_show_subscribe_button.html.erb
<% if @subscription %>
  <% if @subscription.approved == false %>
    <h4>Subscription Pending</h4>
  <% else %>
    <%= form_for @subscription, method: :delete do |f| %>
      <%= f.hidden_field :playlist_id, value: @playlist.id %>
      <%= f.submit "Unsubscribe", :id => "subscribe_to_playlist" %>
    <% end %>
  <% end %>
<% else %>
  <%= form_for Subscription.new do |f| %>
    <%= f.hidden_field :playlist_id, value: @playlist.id %>
    <%= f.submit "Subscribe", :id => "unsubscribe_from_playlist" %>
  <% end %>
<% end %>

app/views/playlists/_tag_cloud.html.erb
<div class="jumbotron">
  <h3>Tags:</h3>
  <% tag_cloud Playlist.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>

app/views/playlists/_tags_playlists_show.html.erb
<p>
  <!-- using raw here. should probably have helper method to escape html -->
  Tags: <%= raw @playlist.tag_list.map { |tag| link_to tag, tag_path(tag) }.join(", ") %>
</p>

app/views/playlists/edit.html.erb
<h1>Edit <% @playlist.name %>:</h1>
<%= form_for(@playlist) do |f| %>

    <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@playlist.errors.count, "error") %> prohibited
        this playlist from being saved:
      </h2>
      <ul>
        <% @playlist.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, :value => @playlist.name %><br>

    <%= f.label :prvt, "I want this playlist to be private." %>
    <%= f.check_box :prvt %><br>

    <%= f.label :locked, "I want to lock this playlist and prevent changes." %>
    <%= f.check_box :locked %><br>

    <%= f.label :tag_list, "Tags (seperated by commas)" %>
    <%= f.text_field :tag_list, :value => @playlist.tag_list.join(", ") %><br>

    <%= f.hidden_field :host_id, :value => current_user.id %>
    <%= f.submit "Save Changes", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Back', @playlist %>

app/views/playlists/index.html.erb
<div id="not-logged-in">
  <div class="row col-md-offset-5">
    <% if @tag %>
      <h1><%= "Playlists tagged with: #{@tag}" %></h1>
    <% else %>
      <h1>Playlists:</h1>
    <% end %>
  </div>

  <div class="index-tag-cloud col-md-5">
    <%= render 'tag_cloud' %>
  </div>

  <div class="col-md-7">
    <table class="table">
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= link_to "#{playlist.name}", playlist %></td>
      </tr>
    </table>
    <% end %>
  </div>
</div>

app/views/playlists/new.html.erb
Create a new playlist:<br>
<%= form_for(@playlist) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :private, "I want this playlist to be private" %>
    <%= f.radio_button :private, true, :checked => false, :value=> true %><br>

    <%= f.label :tag_list, "Tags (seperated by commas)" %>
    <%= f.text_field :tag_list %><br>

    <%= f.hidden_field :host_id, :value => current_user.id %>
    <%= f.submit "Create a new playlist", class: "btn btn-primary" %>
<% end %>
  

app/views/playlists/show.html.erb
<script>
  current_user_is_host = <%= current_user.id == @playlist.host_id %>;
  current_user_name = "<%= "#{current_user.name}" %>";
</script>
<!-- <center><div id="player"></div></center> -->
<script src="http://www.youtube.com/iframe_api"></script>
<script>
    if (<%= @songs.empty? %>) {
      var videoIDs = [
          'i_kF4zLNKio', <%= @songs.html_safe %>
      ];
    }
    else {
      var videoIDs = [
          <%= @songs.html_safe %>
      ];
    }

    var player, currentVideoIndex = 0;
    var whatIsPlaying = 0;
    var songsPlayed = [];

    function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
            height: '450',
            width: '100%',
            events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
            }
        });
    }

    function onPlayerReady(event) {
        event.target.loadVideoById(videoIDs[currentVideoIndex]);
    }

    function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.ENDED) {
          $('#songs-list').find("#" + videoIDs[currentVideoIndex]).parents().eq(2).fadeTo(500,0.2);
          currentVideoIndex++;
          videoIDs.push(songsPlayed);
            if (currentVideoIndex < videoIDs.length) {
               player.loadVideoById(videoIDs[currentVideoIndex]);
            }
        }
        if (event.data == YT.PlayerState.PLAYING) {
          whatIsPlaying = player.getVideoData()['video_id']
          document.getElementById('currently_playing').innerHTML = 'Currently playing: ' + player.getVideoData().title;
        }
    }

    //side-bar tabs:
    $('#interaction').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    })

    $('#chat').click(function (e) {
      e.preventDefault()
      $(this).tab('show')
    })
  
</script>

<div class="container">    

  <div class="row">
    <div id="playlist-header" class="col-xs-13 col-md-9">
      <h1><%= @playlist.name %></h1>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-13 col-md-9">
      
    </div>
    <div id="panel" class="col-xs-5 col-md-3">
      <% if current_user.id == @playlist.host_id %>
        <%= render 'host_panel' %>
      <% else %>  
        <%= render 'like_button' %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div id="main-bar" class="col-xs-12 col-md-8">

      <%= render 'tags_playlists_show' %>
      
      <div style="background-color:black">
        <center><div id="player"></div></center>
      </div>

      <div id="player-underbar">
        <%= render 'show_skip_button' %>
        <div id="currently_playing">
          Currently playing nothing
        </div>
      </div>
      
      <div id="playlist">
        <div id="songs-list">
          <% @playlist.requests.order(:position).each do |request| %>
            <%= div_for request, class: "row" do %>
              <div class="col-md-1 col-xs-1 voting" id="voting-<%= request.id%>">
                <% if !@playlist.locked %>
                  <a class="upvote" id="upvote-<%= request.id%>">
                    <span class="glyphicon glyphicon-chevron-up"></span>
                  </a>
                <% end %>
                <h6 id="vote-count-<%= request.id%>"><%= request.vote_count %></h6>
                <% if !@playlist.locked %>
                  <a class="downvote" id="downvote-<%= request.id%>">
                    <span class="glyphicon glyphicon-chevron-down"></span>
                  </a>
                <% end %>
              </div> 

              <div class="col-md-2 col-xs-3 song-thumbnail">
                <%= image_tag("https://img.youtube.com/vi/#{request.song.uid}/default.jpg", height: '60', width: '80', class: "youtube_thumbnail") %>
              </div>

              <div class="col-md-8 col-xs-14 song-info">
                <p>
                <%= link_to "#{request.song.name}", request.song, id: "#{request.song.uid}", class: "song-uid" %><br>
                <%= "Requested by: #{request.listener.name} "%>
                </p>
              </div>
              
              <% if current_user.id == @playlist.host_id %>
                <a class="delete" id="delete-<%= request.id %>">
                  <span class="glyphicon glyphicon-remove"></span>
                </a>
              <% end %>
            
            <% end %>
          <% end %>
        </div>
        <% if !@playlist.locked %>
          <h2>Add Song:</h2>
          <%= render 'add_song_form' %>
        <% end %>
      </div>
    </div>

    <!-- SIDE BAR: -->
    <div id="playlist-side-bar" class="col-xs-6 col-md-4" role="tabpanel">
      <ul id="side-bar-tabs" class="nav nav-tabs" role="tablist">
        <li role="presentation" class="">
          <a href="#interaction" id="home-tab" role="tab" data-toggle="tab" aria-controls="interaction" aria-expanded="false">Interaction</a>
        </li>
        <li role="presentation" class="active">
          <a href="#chat" role="tab" id="profile-tab" data-toggle="tab" aria-controls="chat" aria-expanded="true">Chat</a>
        </li>
      </ul>
      <div id="myTabContent" class="tab-content">
        <div role="tabpanel" class="tab-pane fade" id="interaction" aria-labelledby="interaction-tab">
          <%= render 'subscription_feature' %>
          <%= render 'like_user_box' %>
        </div>
        <div role="tabpanel" class="tab-pane fade active in" id="chat" aria-labelledby="chat-tab">
          <%= render 'chat_box_and_form' %>
        </div>
      </div>
    </div>

  </div><!-- row -->
</div><!-- container -->